version: 2
jobs:
  build:
    docker:
      - image: xldenis/hakyll:4.12.3.0-ext
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "xxx.cabal" }}
      - run:
          name: Build executable
          command: stack build
      - save_cache:
          paths:
            - .stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "xxx.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec site rebuild
            git checkout master
            git pull --rebase
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
