production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
development:
  sessions:
    default:
      database: xavio_development
      hosts:
        - localhost:27017
      options:
        # consistency: :strong
  options:

test:
  sessions:
    default:
      database: xavio_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
