env:
  cache_generation: 2024-03-04

name: Deploy site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.16.0
    steps:
    - uses: actions/checkout@v3
    - name: Install Zola
      run: |
        curl -sL https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/local/bin
    - name: Build with Zola
      run: zola build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
  deploy:
    needs: build

    permissions:
        pages: write
        id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action