name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v1
      
    - name: Install dependencies
      run: |
        stack --no-terminal --fast --install-ghc test --only-dependencies
    - name: Build
      run: |
        stack build --fast
    - name: Rebuild Site
      run: stack exec site rebuild
