name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true
      
    - name: Install dependencies
      run: |
        stack --no-terminal --install-ghc test --only-dependencies
    - name: Build
      run: |
        stack build --fast
    - name: Rebuild Site
      run: stack exec site rebuild
