env:
  cache_generation: 2024-03-04

name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - id: setup-haskell-stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
    - name: "Cache"
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles(matrix.stack-yaml) }}-${{ env.cache_generation }}
        path: |
          ${{ steps.setup-haskell-stack.outputs.stack-root }}
    - name: Install dependencies
      run: |
        stack --no-terminal --install-ghc test --only-dependencies
    - name: Build
      run: |
        stack build --fast
    - name: Rebuild Site
      run: stack exec site rebuild
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    needs: build

    permissions:
        pages: write
        id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action